// Merkle root parity tests for CO-011a.4 R-MERKLE-PARITY verification.
// Run via:
//   npx tsx lib/merkle.test.ts
//
// Fixture values were generated by running the Go implementation in
// wevibe-hub/internal/chain/merkle.go with identical inputs and verified
// byte-for-byte against this TypeScript port.

import { computeMerkleRoot } from './merkle';

type Vector = {
  name: string;
  leaves: Uint8Array[];
  expected: string;
};

const enc = new TextEncoder();

const vectors: Vector[] = [
  {
    name: 'one leaf ("abc")',
    leaves: [enc.encode('abc')],
    expected: 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad',
  },
  {
    name: 'two leaves ("abc","def")',
    leaves: [enc.encode('abc'), enc.encode('def')],
    expected: 'bef57ec7f53a6d40beb640a780a639c83bc29ac8a9816f1fc6c5c6dcd93c4721',
  },
  {
    name: 'three leaves ("abc","def","ghi") — odd, padded',
    leaves: [enc.encode('abc'), enc.encode('def'), enc.encode('ghi')],
    expected: '3971de445e748ce8f150c12340fb84c991fdb9e7ec4c9cdc85ad17ea2b20b44a',
  },
];

let failed = 0;

async function main() {
  for (const v of vectors) {
    const root = await computeMerkleRoot(v.leaves);
    const ok = root === v.expected;
    if (!ok) failed += 1;
    console.log(
      `${ok ? 'PASS' : 'FAIL'}: ${v.name}\n  got      ${root}\n  expected ${v.expected}`,
    );
  }
  if (failed > 0) {
    console.log(`\nFAILED ${failed} of ${vectors.length} merkle parity vectors`);
    process.exit(1);
  }
  console.log(`\nAll ${vectors.length} merkle parity vectors PASSED`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});