-- This file is a REFERENCE COPY of the current schema.
-- The authoritative schema is defined by the migration files in db/migrations/.
-- Do NOT edit this file for schema changes. Create a new migration instead.

-- WeVibe Network Hub — PostgreSQL Schema
-- Version: 2.0 (CO-253)

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ── Organizations ──────────────────────────────────────────────────────────

CREATE TABLE orgs (
    org_id                      TEXT        PRIMARY KEY,
    leader_pubkey               TEXT        NOT NULL,
    org_name                    TEXT        NOT NULL,
    domain                      TEXT        NOT NULL,
    current_epoch               INTEGER     NOT NULL DEFAULT 0,
    fee_model                   JSONB       NOT NULL DEFAULT '{}',
    egress_mode                 TEXT        NOT NULL DEFAULT 'unrestricted'
                                        CHECK (egress_mode IN ('local_only', 'allowlist', 'unrestricted')),
    required_approvals         INTEGER     NOT NULL DEFAULT 1 CHECK (required_approvals >= 1),
    report_ban_threshold        INTEGER     NOT NULL DEFAULT 3 CHECK (report_ban_threshold >= 1),
    report_vote_threshold       INTEGER     NOT NULL DEFAULT 1 CHECK (report_vote_threshold >= 1),
    allowed_providers           TEXT[]      NOT NULL DEFAULT '{}',
    status                      TEXT        NOT NULL DEFAULT 'active'
                                        CHECK (status IN ('active', 'suspended', 'closed')),
    rotation_status             TEXT        NOT NULL DEFAULT 'active'
                                        CHECK (rotation_status IN ('active', 'rotation_pending')),
    rotation_pending_since      TIMESTAMPTZ,
    stripe_customer_id          TEXT,
    stripe_subscription_id      TEXT,
    last_batch_extraction_at    TIMESTAMPTZ,
    last_chain_submission_at    TIMESTAMPTZ,
    trial_days                  INTEGER     NOT NULL DEFAULT 7,
    chain_registered            BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_orgs_leader ON orgs(leader_pubkey);
CREATE INDEX idx_orgs_status  ON orgs(status);

-- ── Members ────────────────────────────────────────────────────────────────

CREATE TABLE members (
    org_id                      TEXT        NOT NULL REFERENCES orgs(org_id) ON DELETE CASCADE,
    pubkey                      TEXT        NOT NULL,
    x25519_pubkey               TEXT        NOT NULL,
    pre_pubkey                  BYTEA,
    role                        TEXT        NOT NULL
                                            CHECK (role IN ('leader', 'moderator', 'member')),
    join_epoch                  INTEGER     NOT NULL,
    history_access_from_epoch   INTEGER     NOT NULL DEFAULT 0,
    authorized_until_epoch      INTEGER,
    active                      BOOLEAN     NOT NULL DEFAULT TRUE,
    joined_at                   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    wallet_address              TEXT,
    member_tier                 TEXT        NOT NULL DEFAULT 'member'
                                             CHECK (member_tier IN ('trial', 'member', 'premium')),
    dismissed_reports_count     INTEGER     NOT NULL DEFAULT 0,
    is_trial                    BOOLEAN     NOT NULL DEFAULT FALSE,
    trial_expires_at            TIMESTAMP,
    PRIMARY KEY (org_id, pubkey),
    UNIQUE (org_id, wallet_address)
);

CREATE INDEX idx_members_active ON members(org_id, active);
CREATE INDEX idx_members_pubkey ON members(pubkey);
CREATE INDEX idx_members_wallet ON members(wallet_address) WHERE wallet_address IS NOT NULL;

-- ── Epoch manifests ────────────────────────────────────────────────────────

CREATE TABLE epoch_manifests (
    org_id                  TEXT        NOT NULL REFERENCES orgs(org_id) ON DELETE CASCADE,
    epoch_id                INTEGER     NOT NULL,
    pk_mod                  TEXT        NOT NULL,
    umbral_pk               BYTEA,
    previous_manifest_hash  TEXT,
    signed_by               TEXT        NOT NULL,
    signature               TEXT        NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (org_id, epoch_id)
);

-- ── Pending submissions ────────────────────────────────────────────────────
-- Lifecycle: pending → pending_keyword → pending_chain → committed (terminal)
--             └─────────── denied (terminal reject, any stage) ───────────────
-- Valid status values: 'pending', 'pending_keyword', 'pending_chain', 'committed', 'denied'
-- Handler status writes MUST use protocol.SubmissionStatus* constants (protocol/types.go)

CREATE TABLE pending_submissions (
    submission_hash         TEXT        PRIMARY KEY,
    org_id                  TEXT        NOT NULL REFERENCES orgs(org_id),
    epoch_id                INTEGER     NOT NULL,
    contributor_pubkey      TEXT        NOT NULL,
    ciphertext_hex          TEXT        NOT NULL,
    wrapped_dek_mod         TEXT        NOT NULL,
    umbral_capsule          BYTEA,
    umbral_ciphertext       BYTEA,
    contributor_sig         TEXT        NOT NULL,
    stack_hint              TEXT[]      NOT NULL DEFAULT '{}',
    memory_type             TEXT        NOT NULL CHECK (memory_type IN ('correct_implementation', 'negative_signal')),
    status                  TEXT        NOT NULL DEFAULT 'pending'
                                    CHECK (status IN ('pending', 'pending_keyword', 'pending_chain', 'committed', 'denied')),
    denial_reason           TEXT,
    moderator_pubkey        TEXT,
    approved_at             TIMESTAMPTZ,
    extraction_result       JSONB,
    extraction_feedback     TEXT,
    verified_at             TIMESTAMPTZ,
    sanitization_findings   JSONB,
    banned                  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at             TIMESTAMPTZ
);

CREATE INDEX idx_pending_org_status ON pending_submissions(org_id, status);
CREATE INDEX idx_pending_contributor ON pending_submissions(contributor_pubkey);

-- ── Approval votes ─────────────────────────────────────────────────────────

CREATE TABLE approval_votes (
    org_id           TEXT        NOT NULL REFERENCES orgs(org_id) ON DELETE CASCADE,
    submission_hash  TEXT        NOT NULL REFERENCES pending_submissions(submission_hash) ON DELETE CASCADE,
    moderator_pubkey TEXT        NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (org_id, submission_hash, moderator_pubkey)
);

CREATE INDEX idx_votes_org_submission ON approval_votes(org_id, submission_hash);

-- ── Reports ─────────────────────────────────────────────────────────────────

CREATE TABLE reports (
    id                   UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id               TEXT        NOT NULL REFERENCES orgs(org_id) ON DELETE CASCADE,
    memory_cid           TEXT        NOT NULL,
    reporter_pubkey      TEXT        NOT NULL,
    reporter_wallet      TEXT,
    reporter_role        TEXT        NOT NULL DEFAULT 'member'
                                     CHECK (reporter_role IN ('leader', 'moderator', 'member')),
    reason               TEXT        NOT NULL CHECK (reason IN ('incorrect', 'outdated', 'security_risk', 'malicious')),
    note                 TEXT,
    status               TEXT        NOT NULL DEFAULT 'pending'
                                     CHECK (status IN ('pending', 'upheld_pending_tx', 'upheld', 'dismissed', 'dismissed_malicious')),
    resolution           TEXT        CHECK (resolution IN ('upheld', 'dismissed', 'dismissed_malicious') OR resolution IS NULL),
    resolved_by          TEXT,
    resolved_at          TIMESTAMPTZ,
    escalation_votes     JSONB       NOT NULL DEFAULT '[]',
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_reports_org_status ON reports(org_id, status);
CREATE INDEX idx_reports_memory ON reports(org_id, memory_cid);
CREATE INDEX idx_reports_created ON reports(created_at DESC);

-- ── Report votes ───────────────────────────────────────────────────────────
-- Tracks individual votes on reports by moderators/leaders.

CREATE TABLE report_votes (
    org_id       TEXT        NOT NULL REFERENCES orgs(org_id) ON DELETE CASCADE,
    report_id    UUID        NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
    voter_pubkey TEXT        NOT NULL,
    vote         TEXT        NOT NULL CHECK (vote IN ('uphold', 'dismiss', 'dismiss_malicious')),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (org_id, report_id, voter_pubkey)
);

CREATE INDEX idx_report_votes_report ON report_votes(org_id, report_id);

-- ── Rotation buffer ────────────────────────────────────────────────────────
-- Submissions received while org is in rotation_pending state.
-- These are NOT assigned a final epoch and NOT admitted to moderation queue.
-- After rotation completes, they are moved to pending_submissions under the new epoch.

CREATE TABLE rotation_buffer (
    buffer_id           TEXT        PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
    org_id              TEXT        NOT NULL REFERENCES orgs(org_id) ON DELETE CASCADE,
    contributor_pubkey  TEXT        NOT NULL,
    ciphertext_hex      TEXT        NOT NULL,
    wrapped_dek_mod     TEXT        NOT NULL,
    contributor_sig     TEXT        NOT NULL,
    submission_hash     TEXT        NOT NULL,
    stack_hint          TEXT[]      NOT NULL DEFAULT '{}',
    memory_type         TEXT        NOT NULL CHECK (memory_type IN ('correct_implementation', 'negative_signal')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_rotation_buffer_org ON rotation_buffer(org_id);

-- ── Usage receipts ─────────────────────────────────────────────────────────

CREATE TABLE usage_receipts (
    receipt_id          TEXT        PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
    org_id              TEXT        NOT NULL REFERENCES orgs(org_id),
    billing_epoch       INTEGER     NOT NULL,
    access_epochs       INTEGER[]   NOT NULL,
    agent_pubkey        TEXT        NOT NULL,
    query_commitment    TEXT        NOT NULL,
    result_commitment   TEXT        NOT NULL,
    agent_signature     TEXT        NOT NULL,
    node_signature      TEXT        NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_receipts_org_epoch ON usage_receipts(org_id, billing_epoch);

-- ── Audit log ──────────────────────────────────────────────────────────────

CREATE TABLE audit_log (
    id              BIGSERIAL   PRIMARY KEY,
    org_id          TEXT        NOT NULL REFERENCES orgs(org_id),
    epoch_id        INTEGER     NOT NULL,
    event_type      TEXT        NOT NULL,
    actor_pubkey    TEXT        NOT NULL,
    encrypted_entry TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_audit_org_epoch ON audit_log(org_id, epoch_id);

-- ── Credit ledger ───────────────────────────────────────────────────────────

CREATE TABLE org_credits (
    org_id          TEXT        PRIMARY KEY REFERENCES orgs(org_id) ON DELETE CASCADE,
    balance         BIGINT      NOT NULL DEFAULT 0 CHECK (balance >= 0),
    lifetime_used   BIGINT      NOT NULL DEFAULT 0,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE credit_transactions (
    txn_id          BIGSERIAL   PRIMARY KEY,
    org_id          TEXT        NOT NULL REFERENCES orgs(org_id),
    delta           BIGINT      NOT NULL,
    reason          TEXT        NOT NULL,
    receipt_id      TEXT,
    actor           TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_credit_txn_org ON credit_transactions(org_id, created_at DESC);

-- ── Key envelopes ──────────────────────────────────────────────────────────

CREATE TABLE key_envelopes (
    org_id          TEXT        NOT NULL REFERENCES orgs(org_id) ON DELETE CASCADE,
    pubkey          TEXT        NOT NULL,
    epoch_id        INTEGER     NOT NULL,
    enc_envelope    TEXT        NOT NULL,
    search_envelope TEXT        NOT NULL,
    mod_envelope    TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (org_id, pubkey)
);

CREATE INDEX idx_envelopes_org ON key_envelopes(org_id);

-- ── Recovery shares ─────────────────────────────────────────────────────────
-- Sealed Shamir shares for threshold recovery of K_master.
-- Hub stores opaque sealed blobs — cannot read share content.
-- Each share is sealed to a designated holder's X25519 pubkey.

CREATE TABLE recovery_shares (
    org_id              TEXT        NOT NULL REFERENCES orgs(org_id) ON DELETE CASCADE,
    share_index         INTEGER     NOT NULL CHECK (share_index BETWEEN 1 AND 3),
    holder_pubkey       TEXT        NOT NULL,
    sealed_share        TEXT        NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (org_id, share_index)
);

CREATE INDEX idx_recovery_shares_holder ON recovery_shares(holder_pubkey);

-- ── Dashboard keys ─────────────────────────────────────────────────────────
-- Authorized dashboard identities per org.
-- A leader registers a dashboard's Ed25519 pubkey to grant it API access.
-- The dashboard signs every request with this key using the same WeVibe-Signed scheme.

CREATE TABLE dashboard_keys (
    org_id          TEXT        NOT NULL REFERENCES orgs(org_id) ON DELETE CASCADE,
    pubkey          TEXT        NOT NULL,
    label           TEXT        NOT NULL DEFAULT 'dashboard',
    registered_by   TEXT        NOT NULL,
    active          BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (org_id, pubkey)
);

CREATE INDEX idx_dashboard_keys_pubkey ON dashboard_keys(pubkey);

-- ── Serve events ───────────────────────────────────────────────────────────
-- Individual memory serve events reported by the plugin.
-- Accumulated here until batch-submitted to the chain via MsgSubmitServeBatch.

CREATE TABLE serve_events (
    id                  BIGSERIAL   PRIMARY KEY,
    org_id              TEXT        NOT NULL REFERENCES orgs(org_id) ON DELETE CASCADE,
    epoch_id            INTEGER     NOT NULL,
    memory_content_hash TEXT        NOT NULL,
    serve_key           TEXT        NOT NULL,
    contributor_id      TEXT        NOT NULL,
    nullifier           TEXT        NOT NULL,
    model_id            TEXT        NOT NULL DEFAULT '',
    turn_count          INTEGER     NOT NULL DEFAULT 0,
    reporter_pubkey     TEXT        NOT NULL,
    reason              TEXT,
    event_type          TEXT        NOT NULL DEFAULT 'serve'
                                    CHECK (event_type IN ('serve', 'denial')),
    status              TEXT        NOT NULL DEFAULT 'pending'
                                    CHECK (status IN ('pending', 'submitted', 'failed')),
    tx_hash             TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    submitted_at        TIMESTAMPTZ,
    UNIQUE (org_id, nullifier)
);

CREATE INDEX idx_serve_events_org_status ON serve_events(org_id, status);
CREATE INDEX idx_serve_events_org_epoch ON serve_events(org_id, epoch_id);
CREATE INDEX idx_serve_events_org_status_type ON serve_events(org_id, status, event_type);

-- ── Delegate keys ────────────────────────────────────────────────────────────
-- Maps a delegate public key to a wallet address (global, not per-org).
-- Enables a delegate (e.g., an AI agent) to act on behalf of the wallet owner.
-- Per Decision H (CO-011a.4): PK is wallet_address, delegate_address is UNIQUE.

CREATE TABLE delegate_keys (
    wallet_address      TEXT PRIMARY KEY,
    delegate_address    TEXT UNIQUE NOT NULL,
    delegate_pubkey     TEXT NOT NULL,
    grant_tx_hash       TEXT,
    grant_expiration    TIMESTAMPTZ,
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_delegate_keys_delegate_address ON delegate_keys(delegate_address);

-- ── Org keywords ────────────────────────────────────────────────────────────
-- Approved vocabulary per org for memory categorization.

CREATE TABLE org_keywords (
    id          SERIAL PRIMARY KEY,
    org_id      TEXT   NOT NULL REFERENCES orgs(org_id),
    keyword     TEXT   NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deprecated  BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE(org_id, keyword)
);

CREATE INDEX idx_org_keywords_org ON org_keywords(org_id) WHERE NOT deprecated;

-- ── Memory keywords ─────────────────────────────────────────────────────────
-- Keywords assigned to specific memories (joined from org_keywords).

CREATE TABLE memory_keywords (
    memory_cid  TEXT    NOT NULL,
    org_id      TEXT    NOT NULL,
    keyword     TEXT    NOT NULL,
    weight      REAL    NOT NULL DEFAULT 0.0,
    PRIMARY KEY (memory_cid, keyword),
    FOREIGN KEY (org_id, keyword) REFERENCES org_keywords(org_id, keyword)
);

CREATE INDEX idx_memory_keywords_keyword ON memory_keywords(org_id, keyword);

-- ── chain_commit_events ────────────────────────────────────────────────────
-- Records every MsgApproveMemory and MsgReportMemory TX for chain watcher restart-safety.

CREATE TABLE chain_commit_events (
    id                          BIGSERIAL   PRIMARY KEY,
    tx_hash                     TEXT        NOT NULL,
    block_height                BIGINT      NOT NULL,
    block_timestamp             TIMESTAMPTZ NOT NULL,
    action_type                 TEXT        NOT NULL CHECK (action_type IN ('memory_approved', 'report_upheld')),
    org_id                      TEXT        NOT NULL,
    memory_hash                 BYTEA       NOT NULL,
    contributor_pubkey          TEXT        NOT NULL,
    approving_moderators        TEXT[]      NOT NULL DEFAULT '{}',
    upholding_moderators        TEXT[]      NOT NULL DEFAULT '{}',
    committing_leader_pubkey    TEXT        NOT NULL,
    reporter_pubkey             TEXT,
    raw_msg_json                JSONB       NOT NULL,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_tx_memory UNIQUE (tx_hash, memory_hash)
);

CREATE INDEX idx_chain_commit_events_tx_hash ON chain_commit_events(tx_hash);
CREATE INDEX idx_chain_commit_events_org ON chain_commit_events(org_id);
CREATE INDEX idx_chain_commit_events_moderators ON chain_commit_events USING GIN(approving_moderators);
CREATE INDEX idx_chain_commit_events_leader ON chain_commit_events(committing_leader_pubkey);
CREATE INDEX idx_chain_commit_events_action ON chain_commit_events(action_type, created_at DESC);

-- ── watcher_state ───────────────────────────────────────────────────────────
-- Provides restart-safety for chain watcher — tracks last processed block height.

CREATE TABLE watcher_state (
    watcher_name            TEXT        PRIMARY KEY,
    last_seen_block_height BIGINT      NOT NULL,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO watcher_state (watcher_name, last_seen_block_height) VALUES ('chain_commit_events', 0);

-- ── notifications ───────────────────────────────────────────────────────────
-- Activity feed for moderator and member notifications.

CREATE TABLE notifications (
    id              BIGSERIAL   PRIMARY KEY,
    recipient_pubkey TEXT       NOT NULL,
    category        TEXT        NOT NULL,
    title           TEXT        NOT NULL,
    body            TEXT        NOT NULL,
    event_ref       TEXT,
    org_id          TEXT,
    read            BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_notifications_recipient_unread ON notifications(recipient_pubkey, read, created_at DESC);

-- ── notification_preferences ────────────────────────────────────────────────
-- Per-user delivery channel preferences for activity notifications.

CREATE TABLE notification_preferences (
    recipient_pubkey    TEXT        PRIMARY KEY,
    email_address       TEXT        NOT NULL DEFAULT '',
    email_enabled       BOOLEAN     NOT NULL DEFAULT FALSE,
    email_categories    TEXT[]      NOT NULL DEFAULT '{}',
    webhook_url         TEXT        NOT NULL DEFAULT '',
    webhook_enabled     BOOLEAN     NOT NULL DEFAULT FALSE,
    webhook_categories  TEXT[]      NOT NULL DEFAULT '{}',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_notification_preferences_updated_at ON notification_preferences(updated_at DESC);

-- ── join_requests ────────────────────────────────────────────────────────────
-- Zero-friction org join with denial cooldown.

CREATE TABLE join_requests (
    request_id      UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id          TEXT        NOT NULL REFERENCES orgs(org_id) ON DELETE CASCADE,
    requester_pubkey TEXT       NOT NULL,
    pre_pubkey      BYTEA,
    status          TEXT        NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'denied')),
    requested_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reviewed_by     TEXT,
    reviewed_at     TIMESTAMPTZ,
    denial_reason   TEXT,
    cooldown_until  TIMESTAMPTZ
);

CREATE INDEX idx_join_requests_org_pending ON join_requests(org_id) WHERE status = 'pending';
CREATE INDEX idx_join_requests_requester_org ON join_requests(requester_pubkey, org_id);
