// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sidecar.proto

package umbralpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreKFragRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	EpochId       uint64                 `protobuf:"varint,2,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	MemberPk      []byte                 `protobuf:"bytes,3,opt,name=member_pk,json=memberPk,proto3" json:"member_pk,omitempty"`
	Kfrag         []byte                 `protobuf:"bytes,4,opt,name=kfrag,proto3" json:"kfrag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreKFragRequest) Reset() {
	*x = StoreKFragRequest{}
	mi := &file_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreKFragRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreKFragRequest) ProtoMessage() {}

func (x *StoreKFragRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreKFragRequest.ProtoReflect.Descriptor instead.
func (*StoreKFragRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{0}
}

func (x *StoreKFragRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *StoreKFragRequest) GetEpochId() uint64 {
	if x != nil {
		return x.EpochId
	}
	return 0
}

func (x *StoreKFragRequest) GetMemberPk() []byte {
	if x != nil {
		return x.MemberPk
	}
	return nil
}

func (x *StoreKFragRequest) GetKfrag() []byte {
	if x != nil {
		return x.Kfrag
	}
	return nil
}

type StoreKFragResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreKFragResponse) Reset() {
	*x = StoreKFragResponse{}
	mi := &file_sidecar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreKFragResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreKFragResponse) ProtoMessage() {}

func (x *StoreKFragResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreKFragResponse.ProtoReflect.Descriptor instead.
func (*StoreKFragResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{1}
}

type ReEncryptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies which stored kfrag to use.
	OrgId    string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	EpochId  uint64 `protobuf:"varint,2,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	MemberPk []byte `protobuf:"bytes,3,opt,name=member_pk,json=memberPk,proto3" json:"member_pk,omitempty"`
	// Serialized Umbral Capsule from the encrypted content.
	Capsule       []byte `protobuf:"bytes,4,opt,name=capsule,proto3" json:"capsule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReEncryptRequest) Reset() {
	*x = ReEncryptRequest{}
	mi := &file_sidecar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReEncryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReEncryptRequest) ProtoMessage() {}

func (x *ReEncryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReEncryptRequest.ProtoReflect.Descriptor instead.
func (*ReEncryptRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{2}
}

func (x *ReEncryptRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ReEncryptRequest) GetEpochId() uint64 {
	if x != nil {
		return x.EpochId
	}
	return 0
}

func (x *ReEncryptRequest) GetMemberPk() []byte {
	if x != nil {
		return x.MemberPk
	}
	return nil
}

func (x *ReEncryptRequest) GetCapsule() []byte {
	if x != nil {
		return x.Capsule
	}
	return nil
}

type ReEncryptResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized VerifiedCapsuleFrag — the re-encrypted capsule fragment.
	Cfrag         []byte `protobuf:"bytes,1,opt,name=cfrag,proto3" json:"cfrag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReEncryptResponse) Reset() {
	*x = ReEncryptResponse{}
	mi := &file_sidecar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReEncryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReEncryptResponse) ProtoMessage() {}

func (x *ReEncryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReEncryptResponse.ProtoReflect.Descriptor instead.
func (*ReEncryptResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{3}
}

func (x *ReEncryptResponse) GetCfrag() []byte {
	if x != nil {
		return x.Cfrag
	}
	return nil
}

type DeleteKFragsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	OrgId string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Member's PRE public key (serialized Umbral PublicKey).
	MemberPk      []byte `protobuf:"bytes,2,opt,name=member_pk,json=memberPk,proto3" json:"member_pk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKFragsRequest) Reset() {
	*x = DeleteKFragsRequest{}
	mi := &file_sidecar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKFragsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKFragsRequest) ProtoMessage() {}

func (x *DeleteKFragsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKFragsRequest.ProtoReflect.Descriptor instead.
func (*DeleteKFragsRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteKFragsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *DeleteKFragsRequest) GetMemberPk() []byte {
	if x != nil {
		return x.MemberPk
	}
	return nil
}

type DeleteKFragsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of kfrags deleted.
	DeletedCount  uint32 `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKFragsResponse) Reset() {
	*x = DeleteKFragsResponse{}
	mi := &file_sidecar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKFragsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKFragsResponse) ProtoMessage() {}

func (x *DeleteKFragsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKFragsResponse.ProtoReflect.Descriptor instead.
func (*DeleteKFragsResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteKFragsResponse) GetDeletedCount() uint32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type DeleteOrgKFragsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrgKFragsRequest) Reset() {
	*x = DeleteOrgKFragsRequest{}
	mi := &file_sidecar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrgKFragsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrgKFragsRequest) ProtoMessage() {}

func (x *DeleteOrgKFragsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrgKFragsRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrgKFragsRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteOrgKFragsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type DeleteOrgKFragsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  uint32                 `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrgKFragsResponse) Reset() {
	*x = DeleteOrgKFragsResponse{}
	mi := &file_sidecar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrgKFragsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrgKFragsResponse) ProtoMessage() {}

func (x *DeleteOrgKFragsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrgKFragsResponse.ProtoReflect.Descriptor instead.
func (*DeleteOrgKFragsResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteOrgKFragsResponse) GetDeletedCount() uint32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_sidecar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{8}
}

type HealthResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Healthy bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Number of kfrags currently stored.
	KfragCount uint64 `protobuf:"varint,2,opt,name=kfrag_count,json=kfragCount,proto3" json:"kfrag_count,omitempty"`
	// Umbral library version.
	UmbralVersion string `protobuf:"bytes,3,opt,name=umbral_version,json=umbralVersion,proto3" json:"umbral_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_sidecar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetKfragCount() uint64 {
	if x != nil {
		return x.KfragCount
	}
	return 0
}

func (x *HealthResponse) GetUmbralVersion() string {
	if x != nil {
		return x.UmbralVersion
	}
	return ""
}

var File_sidecar_proto protoreflect.FileDescriptor

const file_sidecar_proto_rawDesc = "" +
	"\n" +
	"\rsidecar.proto\x12\tumbral.v1\"x\n" +
	"\x11StoreKFragRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\bepoch_id\x18\x02 \x01(\x04R\aepochId\x12\x1b\n" +
	"\tmember_pk\x18\x03 \x01(\fR\bmemberPk\x12\x14\n" +
	"\x05kfrag\x18\x04 \x01(\fR\x05kfrag\"\x14\n" +
	"\x12StoreKFragResponse\"{\n" +
	"\x10ReEncryptRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\bepoch_id\x18\x02 \x01(\x04R\aepochId\x12\x1b\n" +
	"\tmember_pk\x18\x03 \x01(\fR\bmemberPk\x12\x18\n" +
	"\acapsule\x18\x04 \x01(\fR\acapsule\")\n" +
	"\x11ReEncryptResponse\x12\x14\n" +
	"\x05cfrag\x18\x01 \x01(\fR\x05cfrag\"I\n" +
	"\x13DeleteKFragsRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x1b\n" +
	"\tmember_pk\x18\x02 \x01(\fR\bmemberPk\";\n" +
	"\x14DeleteKFragsResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\rR\fdeletedCount\"/\n" +
	"\x16DeleteOrgKFragsRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\">\n" +
	"\x17DeleteOrgKFragsResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\rR\fdeletedCount\"\x0f\n" +
	"\rHealthRequest\"r\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x1f\n" +
	"\vkfrag_count\x18\x02 \x01(\x04R\n" +
	"kfragCount\x12%\n" +
	"\x0eumbral_version\x18\x03 \x01(\tR\rumbralVersion2\x8c\x03\n" +
	"\rUmbralSidecar\x12I\n" +
	"\n" +
	"StoreKFrag\x12\x1c.umbral.v1.StoreKFragRequest\x1a\x1d.umbral.v1.StoreKFragResponse\x12F\n" +
	"\tReEncrypt\x12\x1b.umbral.v1.ReEncryptRequest\x1a\x1c.umbral.v1.ReEncryptResponse\x12O\n" +
	"\fDeleteKFrags\x12\x1e.umbral.v1.DeleteKFragsRequest\x1a\x1f.umbral.v1.DeleteKFragsResponse\x12X\n" +
	"\x0fDeleteOrgKFrags\x12!.umbral.v1.DeleteOrgKFragsRequest\x1a\".umbral.v1.DeleteOrgKFragsResponse\x12=\n" +
	"\x06Health\x12\x18.umbral.v1.HealthRequest\x1a\x19.umbral.v1.HealthResponseBMZKgithub.com/wevibe-network/wevibe-server/wevibe-hub/internal/umbral/umbralpbb\x06proto3"

var (
	file_sidecar_proto_rawDescOnce sync.Once
	file_sidecar_proto_rawDescData []byte
)

func file_sidecar_proto_rawDescGZIP() []byte {
	file_sidecar_proto_rawDescOnce.Do(func() {
		file_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sidecar_proto_rawDesc), len(file_sidecar_proto_rawDesc)))
	})
	return file_sidecar_proto_rawDescData
}

var file_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_sidecar_proto_goTypes = []any{
	(*StoreKFragRequest)(nil),       // 0: umbral.v1.StoreKFragRequest
	(*StoreKFragResponse)(nil),      // 1: umbral.v1.StoreKFragResponse
	(*ReEncryptRequest)(nil),        // 2: umbral.v1.ReEncryptRequest
	(*ReEncryptResponse)(nil),       // 3: umbral.v1.ReEncryptResponse
	(*DeleteKFragsRequest)(nil),     // 4: umbral.v1.DeleteKFragsRequest
	(*DeleteKFragsResponse)(nil),    // 5: umbral.v1.DeleteKFragsResponse
	(*DeleteOrgKFragsRequest)(nil),  // 6: umbral.v1.DeleteOrgKFragsRequest
	(*DeleteOrgKFragsResponse)(nil), // 7: umbral.v1.DeleteOrgKFragsResponse
	(*HealthRequest)(nil),           // 8: umbral.v1.HealthRequest
	(*HealthResponse)(nil),          // 9: umbral.v1.HealthResponse
}
var file_sidecar_proto_depIdxs = []int32{
	0, // 0: umbral.v1.UmbralSidecar.StoreKFrag:input_type -> umbral.v1.StoreKFragRequest
	2, // 1: umbral.v1.UmbralSidecar.ReEncrypt:input_type -> umbral.v1.ReEncryptRequest
	4, // 2: umbral.v1.UmbralSidecar.DeleteKFrags:input_type -> umbral.v1.DeleteKFragsRequest
	6, // 3: umbral.v1.UmbralSidecar.DeleteOrgKFrags:input_type -> umbral.v1.DeleteOrgKFragsRequest
	8, // 4: umbral.v1.UmbralSidecar.Health:input_type -> umbral.v1.HealthRequest
	1, // 5: umbral.v1.UmbralSidecar.StoreKFrag:output_type -> umbral.v1.StoreKFragResponse
	3, // 6: umbral.v1.UmbralSidecar.ReEncrypt:output_type -> umbral.v1.ReEncryptResponse
	5, // 7: umbral.v1.UmbralSidecar.DeleteKFrags:output_type -> umbral.v1.DeleteKFragsResponse
	7, // 8: umbral.v1.UmbralSidecar.DeleteOrgKFrags:output_type -> umbral.v1.DeleteOrgKFragsResponse
	9, // 9: umbral.v1.UmbralSidecar.Health:output_type -> umbral.v1.HealthResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sidecar_proto_init() }
func file_sidecar_proto_init() {
	if File_sidecar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sidecar_proto_rawDesc), len(file_sidecar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sidecar_proto_goTypes,
		DependencyIndexes: file_sidecar_proto_depIdxs,
		MessageInfos:      file_sidecar_proto_msgTypes,
	}.Build()
	File_sidecar_proto = out.File
	file_sidecar_proto_goTypes = nil
	file_sidecar_proto_depIdxs = nil
}
