// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: sidecar.proto

package umbralpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UmbralSidecar_StoreKFrag_FullMethodName      = "/umbral.v1.UmbralSidecar/StoreKFrag"
	UmbralSidecar_ReEncrypt_FullMethodName       = "/umbral.v1.UmbralSidecar/ReEncrypt"
	UmbralSidecar_DeleteKFrags_FullMethodName    = "/umbral.v1.UmbralSidecar/DeleteKFrags"
	UmbralSidecar_DeleteOrgKFrags_FullMethodName = "/umbral.v1.UmbralSidecar/DeleteOrgKFrags"
	UmbralSidecar_Health_FullMethodName          = "/umbral.v1.UmbralSidecar/Health"
)

// UmbralSidecarClient is the client API for UmbralSidecar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UmbralSidecar provides Proxy Re-Encryption operations via the umbral-pre crate.
// This service runs as a separate process to maintain GPL-3.0 / Apache-2.0 license boundary.
// All byte fields are serialized Umbral types using MessagePack (DefaultSerialize/DefaultDeserialize).
type UmbralSidecarClient interface {
	// StoreKFrag stores a pre-generated kfrag for (org_id, epoch_id, member_pubkey).
	// Used when kfrags are generated on the leader machine.
	StoreKFrag(ctx context.Context, in *StoreKFragRequest, opts ...grpc.CallOption) (*StoreKFragResponse, error)
	// ReEncrypt applies a stored kfrag to a capsule, producing a cfrag.
	// Called by the hub during memory retrieval.
	// Returns an error if no kfrag exists for the specified (org_id, epoch_id, member_pubkey).
	ReEncrypt(ctx context.Context, in *ReEncryptRequest, opts ...grpc.CallOption) (*ReEncryptResponse, error)
	// DeleteKFrags deletes all stored kfrags for a member across all epochs in an org.
	// Called by the hub when a member is removed (triggered by MemberRemoved chain event).
	// Idempotent — returns success even if no kfrags exist.
	DeleteKFrags(ctx context.Context, in *DeleteKFragsRequest, opts ...grpc.CallOption) (*DeleteKFragsResponse, error)
	// DeleteOrgKFrags deletes ALL stored kfrags for an entire org.
	// Called during org dissolution.
	DeleteOrgKFrags(ctx context.Context, in *DeleteOrgKFragsRequest, opts ...grpc.CallOption) (*DeleteOrgKFragsResponse, error)
	// Health returns the sidecar's status.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type umbralSidecarClient struct {
	cc grpc.ClientConnInterface
}

func NewUmbralSidecarClient(cc grpc.ClientConnInterface) UmbralSidecarClient {
	return &umbralSidecarClient{cc}
}

func (c *umbralSidecarClient) StoreKFrag(ctx context.Context, in *StoreKFragRequest, opts ...grpc.CallOption) (*StoreKFragResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreKFragResponse)
	err := c.cc.Invoke(ctx, UmbralSidecar_StoreKFrag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *umbralSidecarClient) ReEncrypt(ctx context.Context, in *ReEncryptRequest, opts ...grpc.CallOption) (*ReEncryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReEncryptResponse)
	err := c.cc.Invoke(ctx, UmbralSidecar_ReEncrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *umbralSidecarClient) DeleteKFrags(ctx context.Context, in *DeleteKFragsRequest, opts ...grpc.CallOption) (*DeleteKFragsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKFragsResponse)
	err := c.cc.Invoke(ctx, UmbralSidecar_DeleteKFrags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *umbralSidecarClient) DeleteOrgKFrags(ctx context.Context, in *DeleteOrgKFragsRequest, opts ...grpc.CallOption) (*DeleteOrgKFragsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteOrgKFragsResponse)
	err := c.cc.Invoke(ctx, UmbralSidecar_DeleteOrgKFrags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *umbralSidecarClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, UmbralSidecar_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UmbralSidecarServer is the server API for UmbralSidecar service.
// All implementations must embed UnimplementedUmbralSidecarServer
// for forward compatibility.
//
// UmbralSidecar provides Proxy Re-Encryption operations via the umbral-pre crate.
// This service runs as a separate process to maintain GPL-3.0 / Apache-2.0 license boundary.
// All byte fields are serialized Umbral types using MessagePack (DefaultSerialize/DefaultDeserialize).
type UmbralSidecarServer interface {
	// StoreKFrag stores a pre-generated kfrag for (org_id, epoch_id, member_pubkey).
	// Used when kfrags are generated on the leader machine.
	StoreKFrag(context.Context, *StoreKFragRequest) (*StoreKFragResponse, error)
	// ReEncrypt applies a stored kfrag to a capsule, producing a cfrag.
	// Called by the hub during memory retrieval.
	// Returns an error if no kfrag exists for the specified (org_id, epoch_id, member_pubkey).
	ReEncrypt(context.Context, *ReEncryptRequest) (*ReEncryptResponse, error)
	// DeleteKFrags deletes all stored kfrags for a member across all epochs in an org.
	// Called by the hub when a member is removed (triggered by MemberRemoved chain event).
	// Idempotent — returns success even if no kfrags exist.
	DeleteKFrags(context.Context, *DeleteKFragsRequest) (*DeleteKFragsResponse, error)
	// DeleteOrgKFrags deletes ALL stored kfrags for an entire org.
	// Called during org dissolution.
	DeleteOrgKFrags(context.Context, *DeleteOrgKFragsRequest) (*DeleteOrgKFragsResponse, error)
	// Health returns the sidecar's status.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedUmbralSidecarServer()
}

// UnimplementedUmbralSidecarServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUmbralSidecarServer struct{}

func (UnimplementedUmbralSidecarServer) StoreKFrag(context.Context, *StoreKFragRequest) (*StoreKFragResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreKFrag not implemented")
}
func (UnimplementedUmbralSidecarServer) ReEncrypt(context.Context, *ReEncryptRequest) (*ReEncryptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReEncrypt not implemented")
}
func (UnimplementedUmbralSidecarServer) DeleteKFrags(context.Context, *DeleteKFragsRequest) (*DeleteKFragsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteKFrags not implemented")
}
func (UnimplementedUmbralSidecarServer) DeleteOrgKFrags(context.Context, *DeleteOrgKFragsRequest) (*DeleteOrgKFragsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteOrgKFrags not implemented")
}
func (UnimplementedUmbralSidecarServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedUmbralSidecarServer) mustEmbedUnimplementedUmbralSidecarServer() {}
func (UnimplementedUmbralSidecarServer) testEmbeddedByValue()                       {}

// UnsafeUmbralSidecarServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UmbralSidecarServer will
// result in compilation errors.
type UnsafeUmbralSidecarServer interface {
	mustEmbedUnimplementedUmbralSidecarServer()
}

func RegisterUmbralSidecarServer(s grpc.ServiceRegistrar, srv UmbralSidecarServer) {
	// If the following call panics, it indicates UnimplementedUmbralSidecarServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UmbralSidecar_ServiceDesc, srv)
}

func _UmbralSidecar_StoreKFrag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreKFragRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UmbralSidecarServer).StoreKFrag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UmbralSidecar_StoreKFrag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UmbralSidecarServer).StoreKFrag(ctx, req.(*StoreKFragRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UmbralSidecar_ReEncrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReEncryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UmbralSidecarServer).ReEncrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UmbralSidecar_ReEncrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UmbralSidecarServer).ReEncrypt(ctx, req.(*ReEncryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UmbralSidecar_DeleteKFrags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKFragsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UmbralSidecarServer).DeleteKFrags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UmbralSidecar_DeleteKFrags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UmbralSidecarServer).DeleteKFrags(ctx, req.(*DeleteKFragsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UmbralSidecar_DeleteOrgKFrags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrgKFragsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UmbralSidecarServer).DeleteOrgKFrags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UmbralSidecar_DeleteOrgKFrags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UmbralSidecarServer).DeleteOrgKFrags(ctx, req.(*DeleteOrgKFragsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UmbralSidecar_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UmbralSidecarServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UmbralSidecar_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UmbralSidecarServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UmbralSidecar_ServiceDesc is the grpc.ServiceDesc for UmbralSidecar service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UmbralSidecar_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "umbral.v1.UmbralSidecar",
	HandlerType: (*UmbralSidecarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreKFrag",
			Handler:    _UmbralSidecar_StoreKFrag_Handler,
		},
		{
			MethodName: "ReEncrypt",
			Handler:    _UmbralSidecar_ReEncrypt_Handler,
		},
		{
			MethodName: "DeleteKFrags",
			Handler:    _UmbralSidecar_DeleteKFrags_Handler,
		},
		{
			MethodName: "DeleteOrgKFrags",
			Handler:    _UmbralSidecar_DeleteOrgKFrags_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _UmbralSidecar_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sidecar.proto",
}
