// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: sidecar.proto

package umbralpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateKeyPairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKeyPairRequest) Reset() {
	*x = GenerateKeyPairRequest{}
	mi := &file_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyPairRequest) ProtoMessage() {}

func (x *GenerateKeyPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyPairRequest.ProtoReflect.Descriptor instead.
func (*GenerateKeyPairRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{0}
}

type GenerateKeyPairResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized Umbral SecretKey (32 bytes, big-endian).
	// SENSITIVE — must be handled as secret material by the caller.
	SecretKey []byte `protobuf:"bytes,1,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	// Serialized Umbral PublicKey (33 bytes, compressed secp256k1 point).
	PublicKey     []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKeyPairResponse) Reset() {
	*x = GenerateKeyPairResponse{}
	mi := &file_sidecar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyPairResponse) ProtoMessage() {}

func (x *GenerateKeyPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyPairResponse.ProtoReflect.Descriptor instead.
func (*GenerateKeyPairResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateKeyPairResponse) GetSecretKey() []byte {
	if x != nil {
		return x.SecretKey
	}
	return nil
}

func (x *GenerateKeyPairResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type GenerateKFragsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Org identifier — used as storage key prefix.
	OrgId string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Epoch identifier — used as storage key component.
	EpochId uint64 `protobuf:"varint,2,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	// Serialized Umbral SecretKey of the epoch (delegating key).
	// SENSITIVE — the sidecar uses this transiently and does NOT store it.
	DelegatingSk []byte `protobuf:"bytes,3,opt,name=delegating_sk,json=delegatingSk,proto3" json:"delegating_sk,omitempty"`
	// Serialized Umbral PublicKey of the member (receiving key).
	ReceivingPk []byte `protobuf:"bytes,4,opt,name=receiving_pk,json=receivingPk,proto3" json:"receiving_pk,omitempty"`
	// Serialized Umbral SecretKey used for signing kfrags.
	// SENSITIVE — the sidecar uses this transiently and does NOT store it.
	SignerSk []byte `protobuf:"bytes,5,opt,name=signer_sk,json=signerSk,proto3" json:"signer_sk,omitempty"`
	// Serialized Umbral PublicKey corresponding to signer_sk (verifying key).
	VerifyingPk   []byte `protobuf:"bytes,6,opt,name=verifying_pk,json=verifyingPk,proto3" json:"verifying_pk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKFragsRequest) Reset() {
	*x = GenerateKFragsRequest{}
	mi := &file_sidecar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKFragsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKFragsRequest) ProtoMessage() {}

func (x *GenerateKFragsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKFragsRequest.ProtoReflect.Descriptor instead.
func (*GenerateKFragsRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateKFragsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *GenerateKFragsRequest) GetEpochId() uint64 {
	if x != nil {
		return x.EpochId
	}
	return 0
}

func (x *GenerateKFragsRequest) GetDelegatingSk() []byte {
	if x != nil {
		return x.DelegatingSk
	}
	return nil
}

func (x *GenerateKFragsRequest) GetReceivingPk() []byte {
	if x != nil {
		return x.ReceivingPk
	}
	return nil
}

func (x *GenerateKFragsRequest) GetSignerSk() []byte {
	if x != nil {
		return x.SignerSk
	}
	return nil
}

func (x *GenerateKFragsRequest) GetVerifyingPk() []byte {
	if x != nil {
		return x.VerifyingPk
	}
	return nil
}

type GenerateKFragsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized VerifiedKeyFrag. Stored internally by the sidecar.
	// Returned to caller for backup/audit purposes only.
	Kfrag         []byte `protobuf:"bytes,1,opt,name=kfrag,proto3" json:"kfrag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKFragsResponse) Reset() {
	*x = GenerateKFragsResponse{}
	mi := &file_sidecar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKFragsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKFragsResponse) ProtoMessage() {}

func (x *GenerateKFragsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKFragsResponse.ProtoReflect.Descriptor instead.
func (*GenerateKFragsResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateKFragsResponse) GetKfrag() []byte {
	if x != nil {
		return x.Kfrag
	}
	return nil
}

type ReEncryptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies which stored kfrag to use.
	OrgId    string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	EpochId  uint64 `protobuf:"varint,2,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	MemberPk []byte `protobuf:"bytes,3,opt,name=member_pk,json=memberPk,proto3" json:"member_pk,omitempty"`
	// Serialized Umbral Capsule from the encrypted content.
	Capsule       []byte `protobuf:"bytes,4,opt,name=capsule,proto3" json:"capsule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReEncryptRequest) Reset() {
	*x = ReEncryptRequest{}
	mi := &file_sidecar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReEncryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReEncryptRequest) ProtoMessage() {}

func (x *ReEncryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReEncryptRequest.ProtoReflect.Descriptor instead.
func (*ReEncryptRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{4}
}

func (x *ReEncryptRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ReEncryptRequest) GetEpochId() uint64 {
	if x != nil {
		return x.EpochId
	}
	return 0
}

func (x *ReEncryptRequest) GetMemberPk() []byte {
	if x != nil {
		return x.MemberPk
	}
	return nil
}

func (x *ReEncryptRequest) GetCapsule() []byte {
	if x != nil {
		return x.Capsule
	}
	return nil
}

type ReEncryptResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized VerifiedCapsuleFrag — the re-encrypted capsule fragment.
	Cfrag         []byte `protobuf:"bytes,1,opt,name=cfrag,proto3" json:"cfrag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReEncryptResponse) Reset() {
	*x = ReEncryptResponse{}
	mi := &file_sidecar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReEncryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReEncryptResponse) ProtoMessage() {}

func (x *ReEncryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReEncryptResponse.ProtoReflect.Descriptor instead.
func (*ReEncryptResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{5}
}

func (x *ReEncryptResponse) GetCfrag() []byte {
	if x != nil {
		return x.Cfrag
	}
	return nil
}

type DeleteKFragsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	OrgId string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Member's PRE public key (serialized Umbral PublicKey).
	MemberPk      []byte `protobuf:"bytes,2,opt,name=member_pk,json=memberPk,proto3" json:"member_pk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKFragsRequest) Reset() {
	*x = DeleteKFragsRequest{}
	mi := &file_sidecar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKFragsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKFragsRequest) ProtoMessage() {}

func (x *DeleteKFragsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKFragsRequest.ProtoReflect.Descriptor instead.
func (*DeleteKFragsRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteKFragsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *DeleteKFragsRequest) GetMemberPk() []byte {
	if x != nil {
		return x.MemberPk
	}
	return nil
}

type DeleteKFragsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of kfrags deleted.
	DeletedCount  uint32 `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKFragsResponse) Reset() {
	*x = DeleteKFragsResponse{}
	mi := &file_sidecar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKFragsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKFragsResponse) ProtoMessage() {}

func (x *DeleteKFragsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKFragsResponse.ProtoReflect.Descriptor instead.
func (*DeleteKFragsResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteKFragsResponse) GetDeletedCount() uint32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type DeleteOrgKFragsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrgKFragsRequest) Reset() {
	*x = DeleteOrgKFragsRequest{}
	mi := &file_sidecar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrgKFragsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrgKFragsRequest) ProtoMessage() {}

func (x *DeleteOrgKFragsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrgKFragsRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrgKFragsRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteOrgKFragsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type DeleteOrgKFragsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  uint32                 `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrgKFragsResponse) Reset() {
	*x = DeleteOrgKFragsResponse{}
	mi := &file_sidecar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrgKFragsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrgKFragsResponse) ProtoMessage() {}

func (x *DeleteOrgKFragsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrgKFragsResponse.ProtoReflect.Descriptor instead.
func (*DeleteOrgKFragsResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteOrgKFragsResponse) GetDeletedCount() uint32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_sidecar_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{10}
}

type HealthResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Healthy bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Number of kfrags currently stored.
	KfragCount uint64 `protobuf:"varint,2,opt,name=kfrag_count,json=kfragCount,proto3" json:"kfrag_count,omitempty"`
	// Umbral library version.
	UmbralVersion string `protobuf:"bytes,3,opt,name=umbral_version,json=umbralVersion,proto3" json:"umbral_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_sidecar_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{11}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetKfragCount() uint64 {
	if x != nil {
		return x.KfragCount
	}
	return 0
}

func (x *HealthResponse) GetUmbralVersion() string {
	if x != nil {
		return x.UmbralVersion
	}
	return ""
}

var File_sidecar_proto protoreflect.FileDescriptor

const file_sidecar_proto_rawDesc = "" +
	"\n" +
	"\rsidecar.proto\x12\tumbral.v1\"\x18\n" +
	"\x16GenerateKeyPairRequest\"W\n" +
	"\x17GenerateKeyPairResponse\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x01 \x01(\fR\tsecretKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"\xd1\x01\n" +
	"\x15GenerateKFragsRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\bepoch_id\x18\x02 \x01(\x04R\aepochId\x12#\n" +
	"\rdelegating_sk\x18\x03 \x01(\fR\fdelegatingSk\x12!\n" +
	"\freceiving_pk\x18\x04 \x01(\fR\vreceivingPk\x12\x1b\n" +
	"\tsigner_sk\x18\x05 \x01(\fR\bsignerSk\x12!\n" +
	"\fverifying_pk\x18\x06 \x01(\fR\vverifyingPk\".\n" +
	"\x16GenerateKFragsResponse\x12\x14\n" +
	"\x05kfrag\x18\x01 \x01(\fR\x05kfrag\"{\n" +
	"\x10ReEncryptRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\bepoch_id\x18\x02 \x01(\x04R\aepochId\x12\x1b\n" +
	"\tmember_pk\x18\x03 \x01(\fR\bmemberPk\x12\x18\n" +
	"\acapsule\x18\x04 \x01(\fR\acapsule\")\n" +
	"\x11ReEncryptResponse\x12\x14\n" +
	"\x05cfrag\x18\x01 \x01(\fR\x05cfrag\"I\n" +
	"\x13DeleteKFragsRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x1b\n" +
	"\tmember_pk\x18\x02 \x01(\fR\bmemberPk\";\n" +
	"\x14DeleteKFragsResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\rR\fdeletedCount\"/\n" +
	"\x16DeleteOrgKFragsRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\">\n" +
	"\x17DeleteOrgKFragsResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\rR\fdeletedCount\"\x0f\n" +
	"\rHealthRequest\"r\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x1f\n" +
	"\vkfrag_count\x18\x02 \x01(\x04R\n" +
	"kfragCount\x12%\n" +
	"\x0eumbral_version\x18\x03 \x01(\tR\rumbralVersion2\xf2\x03\n" +
	"\rUmbralSidecar\x12X\n" +
	"\x0fGenerateKeyPair\x12!.umbral.v1.GenerateKeyPairRequest\x1a\".umbral.v1.GenerateKeyPairResponse\x12U\n" +
	"\x0eGenerateKFrags\x12 .umbral.v1.GenerateKFragsRequest\x1a!.umbral.v1.GenerateKFragsResponse\x12F\n" +
	"\tReEncrypt\x12\x1b.umbral.v1.ReEncryptRequest\x1a\x1c.umbral.v1.ReEncryptResponse\x12O\n" +
	"\fDeleteKFrags\x12\x1e.umbral.v1.DeleteKFragsRequest\x1a\x1f.umbral.v1.DeleteKFragsResponse\x12X\n" +
	"\x0fDeleteOrgKFrags\x12!.umbral.v1.DeleteOrgKFragsRequest\x1a\".umbral.v1.DeleteOrgKFragsResponse\x12=\n" +
	"\x06Health\x12\x18.umbral.v1.HealthRequest\x1a\x19.umbral.v1.HealthResponseB;Z9github.com/wevibe-network/wevibe-server/wevibe-hub/internal/umbral/umbralpbb\x06proto3"

var (
	file_sidecar_proto_rawDescOnce sync.Once
	file_sidecar_proto_rawDescData []byte
)

func file_sidecar_proto_rawDescGZIP() []byte {
	file_sidecar_proto_rawDescOnce.Do(func() {
		file_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sidecar_proto_rawDesc), len(file_sidecar_proto_rawDesc)))
	})
	return file_sidecar_proto_rawDescData
}

var file_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_sidecar_proto_goTypes = []any{
	(*GenerateKeyPairRequest)(nil),  // 0: umbral.v1.GenerateKeyPairRequest
	(*GenerateKeyPairResponse)(nil), // 1: umbral.v1.GenerateKeyPairResponse
	(*GenerateKFragsRequest)(nil),   // 2: umbral.v1.GenerateKFragsRequest
	(*GenerateKFragsResponse)(nil),  // 3: umbral.v1.GenerateKFragsResponse
	(*ReEncryptRequest)(nil),        // 4: umbral.v1.ReEncryptRequest
	(*ReEncryptResponse)(nil),       // 5: umbral.v1.ReEncryptResponse
	(*DeleteKFragsRequest)(nil),     // 6: umbral.v1.DeleteKFragsRequest
	(*DeleteKFragsResponse)(nil),    // 7: umbral.v1.DeleteKFragsResponse
	(*DeleteOrgKFragsRequest)(nil),  // 8: umbral.v1.DeleteOrgKFragsRequest
	(*DeleteOrgKFragsResponse)(nil), // 9: umbral.v1.DeleteOrgKFragsResponse
	(*HealthRequest)(nil),           // 10: umbral.v1.HealthRequest
	(*HealthResponse)(nil),          // 11: umbral.v1.HealthResponse
}
var file_sidecar_proto_depIdxs = []int32{
	0,  // 0: umbral.v1.UmbralSidecar.GenerateKeyPair:input_type -> umbral.v1.GenerateKeyPairRequest
	2,  // 1: umbral.v1.UmbralSidecar.GenerateKFrags:input_type -> umbral.v1.GenerateKFragsRequest
	4,  // 2: umbral.v1.UmbralSidecar.ReEncrypt:input_type -> umbral.v1.ReEncryptRequest
	6,  // 3: umbral.v1.UmbralSidecar.DeleteKFrags:input_type -> umbral.v1.DeleteKFragsRequest
	8,  // 4: umbral.v1.UmbralSidecar.DeleteOrgKFrags:input_type -> umbral.v1.DeleteOrgKFragsRequest
	10, // 5: umbral.v1.UmbralSidecar.Health:input_type -> umbral.v1.HealthRequest
	1,  // 6: umbral.v1.UmbralSidecar.GenerateKeyPair:output_type -> umbral.v1.GenerateKeyPairResponse
	3,  // 7: umbral.v1.UmbralSidecar.GenerateKFrags:output_type -> umbral.v1.GenerateKFragsResponse
	5,  // 8: umbral.v1.UmbralSidecar.ReEncrypt:output_type -> umbral.v1.ReEncryptResponse
	7,  // 9: umbral.v1.UmbralSidecar.DeleteKFrags:output_type -> umbral.v1.DeleteKFragsResponse
	9,  // 10: umbral.v1.UmbralSidecar.DeleteOrgKFrags:output_type -> umbral.v1.DeleteOrgKFragsResponse
	11, // 11: umbral.v1.UmbralSidecar.Health:output_type -> umbral.v1.HealthResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_sidecar_proto_init() }
func file_sidecar_proto_init() {
	if File_sidecar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sidecar_proto_rawDesc), len(file_sidecar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sidecar_proto_goTypes,
		DependencyIndexes: file_sidecar_proto_depIdxs,
		MessageInfos:      file_sidecar_proto_msgTypes,
	}.Build()
	File_sidecar_proto = out.File
	file_sidecar_proto_goTypes = nil
	file_sidecar_proto_depIdxs = nil
}
